/**
 * Copyright 2020 d-fens GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 28/10/2020 15:42:56
namespace biz.dfch.CS.SampleIPA.StockManagement.API.Models
{
    /// <summary>
    /// There are no comments for ProductsSingle in the schema.
    /// </summary>
    public partial class ProductsSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Products>
    {
        /// <summary>
        /// Initialize a new ProductsSingle object.
        /// </summary>
        public ProductsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductsSingle object.
        /// </summary>
        public ProductsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductsSingle object.
        /// </summary>
        public ProductsSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Products> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle Category
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Category == null))
                {
                    this._Category = new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle(this.Context, GetPath("Category"));
                }
                return this._Category;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle _Category;
    }
    /// <summary>
    /// There are no comments for Products in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Products : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Products object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="pricePerPiece">Initial value of PricePerPiece.</param>
        /// <param name="weightInKg">Initial value of WeightInKg.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Products CreateProducts(int ID, int quantity, decimal pricePerPiece, decimal weightInKg)
        {
            Products products = new Products();
            products.Id = ID;
            products.Quantity = quantity;
            products.PricePerPiece = pricePerPiece;
            products.WeightInKg = weightInKg;
            return products;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MaterialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string MaterialNumber
        {
            get
            {
                return this._MaterialNumber;
            }
            set
            {
                this.OnMaterialNumberChanging(value);
                this._MaterialNumber = value;
                this.OnMaterialNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MaterialNumber;
        partial void OnMaterialNumberChanging(string value);
        partial void OnMaterialNumberChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property PricePerPiece in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual decimal PricePerPiece
        {
            get
            {
                return this._PricePerPiece;
            }
            set
            {
                this.OnPricePerPieceChanging(value);
                this._PricePerPiece = value;
                this.OnPricePerPieceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _PricePerPiece;
        partial void OnPricePerPieceChanging(decimal value);
        partial void OnPricePerPieceChanged();
        /// <summary>
        /// There are no comments for Property WeightInKg in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual decimal WeightInKg
        {
            get
            {
                return this._WeightInKg;
            }
            set
            {
                this.OnWeightInKgChanging(value);
                this._WeightInKg = value;
                this.OnWeightInKgChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _WeightInKg;
        partial void OnWeightInKgChanging(decimal value);
        partial void OnWeightInKgChanged();
        /// <summary>
        /// There are no comments for Property CategoryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> CategoryId
        {
            get
            {
                return this._CategoryId;
            }
            set
            {
                this.OnCategoryIdChanging(value);
                this._CategoryId = value;
                this.OnCategoryIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CategoryId;
        partial void OnCategoryIdChanging(global::System.Nullable<int> value);
        partial void OnCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories _Category;
        partial void OnCategoryChanging(global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories value);
        partial void OnCategoryChanged();
    }
    /// <summary>
    /// There are no comments for BookingsSingle in the schema.
    /// </summary>
    public partial class BookingsSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Bookings>
    {
        /// <summary>
        /// Initialize a new BookingsSingle object.
        /// </summary>
        public BookingsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BookingsSingle object.
        /// </summary>
        public BookingsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BookingsSingle object.
        /// </summary>
        public BookingsSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Bookings> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle Product
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Product == null))
                {
                    this._Product = new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle(this.Context, GetPath("Product"));
                }
                return this._Product;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle _Product;
    }
    /// <summary>
    /// There are no comments for Bookings in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Bookings : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Bookings object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="amount">Initial value of Amount.</param>
        /// <param name="dataTime">Initial value of DataTime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Bookings CreateBookings(int ID, int amount, global::System.DateTimeOffset dataTime)
        {
            Bookings bookings = new Bookings();
            bookings.Id = ID;
            bookings.Amount = amount;
            bookings.DataTime = dataTime;
            return bookings;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Amount;
        partial void OnAmountChanging(int value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property DataTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset DataTime
        {
            get
            {
                return this._DataTime;
            }
            set
            {
                this.OnDataTimeChanging(value);
                this._DataTime = value;
                this.OnDataTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _DataTime;
        partial void OnDataTimeChanging(global::System.DateTimeOffset value);
        partial void OnDataTimeChanged();
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ProductId;
        partial void OnProductIdChanging(global::System.Nullable<int> value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this.OnProductChanging(value);
                this._Product = value;
                this.OnProductChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products _Product;
        partial void OnProductChanging(global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products value);
        partial void OnProductChanged();
    }
    /// <summary>
    /// There are no comments for CategoriesSingle in the schema.
    /// </summary>
    public partial class CategoriesSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Categories>
    {
        /// <summary>
        /// Initialize a new CategoriesSingle object.
        /// </summary>
        public CategoriesSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CategoriesSingle object.
        /// </summary>
        public CategoriesSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CategoriesSingle object.
        /// </summary>
        public CategoriesSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Categories> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Categories in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Categories : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Categories object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Categories CreateCategories(int ID)
        {
            Categories categories = new Categories();
            categories.Id = ID;
            return categories;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products as global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products as global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.ProductsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings as global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.BookingsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.BookingsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.BookingsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings as global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.BookingsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.BookingsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.BookingsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories as global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories as global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.CategoriesSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products> _Products;
        /// <summary>
        /// There are no comments for Bookings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings> Bookings
        {
            get
            {
                if ((this._Bookings == null))
                {
                    this._Bookings = base.CreateQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings>("Bookings");
                }
                return this._Bookings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings> _Bookings;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories>("Categories");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories> _Categories;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToProducts(global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Products products)
        {
            base.AddObject("Products", products);
        }
        /// <summary>
        /// There are no comments for Bookings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToBookings(global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Bookings bookings)
        {
            base.AddObject("Bookings", bookings);
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCategories(global::biz.dfch.CS.SampleIPA.StockManagement.API.Models.Categories categories)
        {
            base.AddObject("Categories", categories);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData Service StockmanagementCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
